[package]
name = "reactive"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_SystemServices"] }
libc = "0.2"
